"""A local stand-in for the official 8-circuit set.

Only Bell and GHZ-3 ship publicly; the other six are generated by the graders
from a private seed. These reproductions have the same *shape* — GHZ-5, QFT-4,
Grover-3 and three random circuits over the 12-gate whitelist — so the pipeline
gets exercised on cu1, ccx, swap and parametrised rotations long before the
hidden set does.

Ideal distributions come from :mod:`loomq.reference`, never from a stored file.
"""

import math
import random
from pathlib import Path
from typing import Dict

from .gates import SIGNATURES, WHITELIST

CIRCUIT_DIR = Path(__file__).resolve().parent.parent / "circuits"


def _measure_all(n_qubits: int) -> str:
    return "\n".join("measure q[%d] -> c[%d];" % (i, i) for i in range(n_qubits))


def program(n_qubits: int, body: str) -> str:
    return (
        'OPENQASM 2.0;\ninclude "qelib1.inc";\nqreg q[%d];\ncreg c[%d];\n%s\n%s\n'
        % (n_qubits, n_qubits, body, _measure_all(n_qubits))
    )


def ghz(n_qubits: int) -> str:
    body = ["h q[0];"] + ["cx q[%d],q[%d];" % (i, i + 1) for i in range(n_qubits - 1)]
    return program(n_qubits, "\n".join(body))


def qft(n_qubits: int = 4) -> str:
    """QFT over a non-uniform input state: exercises cu1 and swap."""
    body = ["x q[0];", "h q[2];"] if n_qubits >= 3 else ["x q[0];"]
    for target in range(n_qubits):
        body.append("h q[%d];" % target)
        for control in range(target + 1, n_qubits):
            body.append(
                "cu1(pi/%d) q[%d], q[%d];" % (2 ** (control - target), control, target)
            )
    for i in range(n_qubits // 2):
        body.append("swap q[%d], q[%d];" % (i, n_qubits - 1 - i))
    return program(n_qubits, "\n".join(body))


def grover3() -> str:
    """3-qubit Grover marking |111>: exercises ccx."""
    body = ["h q[0];", "h q[1];", "h q[2];"]
    for _ in range(2):
        body += ["h q[2];", "ccx q[0], q[1], q[2];", "h q[2];"]
        body += ["h q[0];", "h q[1];", "h q[2];"]
        body += ["x q[0];", "x q[1];", "x q[2];"]
        body += ["h q[2];", "ccx q[0], q[1], q[2];", "h q[2];"]
        body += ["x q[0];", "x q[1];", "x q[2];"]
        body += ["h q[0];", "h q[1];", "h q[2];"]
    return program(3, "\n".join(body))


def random_circuit(seed: int, n_qubits: int = 4, length: int = 24) -> str:
    """Deterministic random circuit drawn from the 12-gate whitelist."""
    rng = random.Random(seed)
    names = sorted(WHITELIST)
    body = []
    while len(body) < length:
        name = rng.choice(names)
        arity, n_params = SIGNATURES[name]
        if arity > n_qubits:
            continue
        qubits = rng.sample(range(n_qubits), arity)
        params = (
            "(%s)" % ", ".join(repr(rng.uniform(-math.pi, math.pi)) for _ in range(n_params))
            if n_params
            else ""
        )
        body.append("%s%s %s;" % (name, params, ", ".join("q[%d]" % q for q in qubits)))
    return program(n_qubits, "\n".join(body))


def bit_order_probe() -> str:
    """The one circuit Bell and GHZ cannot replace.

    Both public circuits are symmetric under bit reversal, so a backend whose
    counts are reversed still scores fidelity 1.0 on them. ``x q[0]`` must
    produce exactly ``{"01": shots}``.
    """
    return program(2, "x q[0];")


def suite() -> Dict[str, str]:
    """Public circuits from disk plus local reproductions of the hidden ones."""
    circuits = {
        "bit_order_probe": bit_order_probe(),
        "bell": (CIRCUIT_DIR / "bell.qasm").read_text(encoding="utf-8"),
        "ghz3": (CIRCUIT_DIR / "ghz3.qasm").read_text(encoding="utf-8"),
        "ghz5": ghz(5),
        "qft4": qft(4),
        "grover3": grover3(),
        "random1": random_circuit(1),
        "random2": random_circuit(2),
        "random3": random_circuit(3, n_qubits=3),
    }
    return circuits
